### ISSUE TITLE
Halting due to insufficient variants to estimate contamination

### ISSUE THREAD

**Issue by leehart** [malariagen/vector-tools#22]
It looks like 11 of the samples from AG1000G-GN-B are failing to get past `scripts/estimate_contamination.py`,
due to `Insufficient variants meet criteria to compute contamination.`
(line 380)

NH suggests writing NA instead of halting with an error.

Glancing at the code, it looks like the error is actually thrown downstream, as a side-effect, rather than directly due to `minimum_minor_af < 0`, which just logs and breaks the while-loop.

E.g. log
```
Selecting variants on which to perform analysis
Insufficient variants meet criteria to compute contamination. n=28, min=50000
Traceback (most recent call last):
  File "/kwiat/2/coluzzi/observatory/production/vo_agam/qc/.snakemake/scripts/tmp0oc2tfi0.estimate_contamination.py", line 422, in <module>
    main()
  File "/kwiat/2/coluzzi/observatory/production/vo_agam/qc/.snakemake/scripts/tmp0oc2tfi0.estimate_contamination.py", line 418, in main
    plot_allele_balance(flt_gt, flt_ad, output_png, res.iloc[0])
  File "/kwiat/2/coluzzi/observatory/production/vo_agam/qc/.snakemake/scripts/tmp0oc2tfi0.estimate_contamination.py", line 194, in plot_allele_balance
    mac1, mac2 = altref[:, 0], altref[:, 1]
IndexError: too many indices for array
```

**Comment by hardingnj** [comment]
Thanks Lee. 

This is a bug where the final `plot_allele_balance` function should be nested in the loop that ends at line `409`. 

ie if insufficient variants: do not plot!

**Comment by hardingnj** [comment]
ie the two lines:
https://github.com/malariagen/vector-tools/blob/7fa4ae6bea7832f6a885d9acf2b494029494a2ed/scripts/estimate_contamination.py#L413

Should be in the same block as https://github.com/malariagen/vector-tools/blob/7fa4ae6bea7832f6a885d9acf2b494029494a2ed/scripts/estimate_contamination.py#L409

**Comment by leehart** [comment]
Also blocks sample QC for AG1000G-CM-A (1 sample).
